---
title: "Death Number Distribution"
author: "Fatemeh Kazemi"
date: "2/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(here)
```

```{r}
dirUSSpatial <- 'C:\\Users\\fkazem01\\Desktop\\Projects\\USA Spatial\\data\\processed\\'
load(paste0(dirUSSpatial,'state-region.RDa'))
load(here('data','processed','dead-enrollee.RDa'))
```

```{r Outcome to Cause }
Outcome.to.Cause <- tribble(
  ~Cause, ~Outcome,
  "All-Cause", "allcuz",
  "Non-Accidental", "nacc",
  "Accidental", "acc",
  "Cardiovascular", "cvd",
  "IHD", "ihd",
  "CHF", "chf",
  "CBV", "cbv",
  "Respiratory", "resp",
  "COPD", "copd",
  "Pneumonia", "pneu",
  "URI", "uri",
  "ARDS", "ards",
  "Cancer", "canc",
  "Lung Cancer", "lungc",
  "Sepsis", "seps",
  "Vascular dementia", "VaD",
  "Alzheimer", "AD",
  "Neurodegeneration", "NeD",
  "Unspecified Dementia", "UsD",
  "Type1 Diabetes", "diabt1",
  "Type2 Diabetes", "diabt2",
  "Diabetes", "diab",
  "Kidney Disease", "kidn"
)
```

```{r data}
#Done
dt.dead.enrollee <- read.csv(
  here('data', 'processed','enrollee_pm_dead.csv'))

save(dt.dead.enrollee, file = here('data','processed','dead-enrollee.RDa'))

dt.dead.enrollee <- dt.state.region %>% 
  transmute(state = State,
            region = Region.IV) %>% 
  right_join(dt.dead.enrollee)
```

# PM2.5
```{r - PM2.5}
## Total Base
x1 <- dt.dead.enrollee %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Total", 
         Value = "Base") %>% 
  select(Subgroup, Value, everything())

## Total SES
x1a <- dt.dead.enrollee %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Total", 
         Value = "SES") %>% 
  select(Subgroup, Value, everything())

## Total Residual
x1b <- dt.dead.enrollee %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Total", 
         Value = "Residual") %>% 
  select(Subgroup, Value, everything())

## Age
x2 <- dt.dead.enrollee %>% 
  group_by(ENROLLEE_AGE > 75) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Age", 
         Value = ifelse(`ENROLLEE_AGE > 75` == "FALSE", "LE75", "M75")) %>% 
  select(Subgroup, Value, everything(), -`ENROLLEE_AGE > 75`)

## Sex
x3 <- dt.dead.enrollee %>% 
  group_by(sex) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Sex", 
         Value = sex) %>% 
  select(Subgroup, Value, everything(), -sex)

## Race
x4 <- dt.dead.enrollee %>% 
  group_by(race) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Race", 
         Value = race) %>% 
  select(Subgroup, Value, everything(), -race)

## Urbanicity
x5 <- dt.dead.enrollee %>% 
  group_by(urban) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Urbanicity", 
         Value = ifelse(urban == 1, "urban", "nonurban")) %>% 
  select(Subgroup, Value, everything(), -urban)

## SES Category
x6 <- dt.dead.enrollee %>% 
  group_by(ses_tertile) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "SES Cat", 
         Value = ifelse(ses_tertile == 0, "L",
                        ifelse(ses_tertile == 1, "M", "H"))) %>% 
  select(Subgroup, Value, everything(), -ses_tertile)

## BRFSS Base
x7 <- dt.dead.enrollee %>% 
  filter(!is.na(X_bmi_Mean)) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "BRFSS", 
         Value = "brfss0") %>% 
  select(Subgroup, Value, everything())

## BRFSS Adj
x7a <- dt.dead.enrollee %>% 
  filter(!is.na(X_bmi_Mean)) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "BRFSS", 
         Value = "brfss") %>% 
  select(Subgroup, Value, everything())

## RC4
x8 <- dt.dead.enrollee %>% 
  summarise(across(cvd_rc:kidn_rc, sum)) %>% 
  mutate(Subgroup = "Total", 
         Value = "RC4") %>% 
  select(Subgroup, Value, everything())

colnames(x8) <-  sub("_rc*", "", colnames(x8))

## Region
x9 <- dt.dead.enrollee %>% 
  group_by(region) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Region", 
         Value = ifelse(region == 1, "W",
                        ifelse(region == 2, "MW", 
                               ifelse(region == 3, "S", "NE")))) %>% 
  select(Subgroup, Value, everything(), -region)

## Race Urban
x10 <- dt.dead.enrollee %>% 
  filter(urban == 1) %>% 
  group_by(race) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Race Urban", 
         Value = race) %>% 
  select(Subgroup, Value, everything(), -race)

## Race Non-urban
x11 <- dt.dead.enrollee %>% 
  filter(urban == 0) %>% 
  group_by(race) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Race Non-urban", 
         Value = race) %>% 
  select(Subgroup, Value, everything(), -race)

## Combine
x <- x1 %>% 
  add_row(x1a) %>% 
  add_row(x1b) %>% 
  add_row(x2) %>% 
  add_row(x3) %>% 
  add_row(x4) %>% 
  add_row(x5) %>% 
  add_row(x6) %>% 
  add_row(x7) %>% 
  add_row(x7a) %>% 
  add_row(x8) %>% 
  add_row(x9) %>% 
  add_row(x10) %>% 
  add_row(x11) %>% 
  mutate(Index = "PM25") %>% 
  select(Index, everything())
```

# NO2
```{r - NO2}
## Total Base
y1 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Total", 
         Value = "Base") %>% 
  select(Subgroup, Value, everything())

## Total SES
y1a <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Total", 
         Value = "SES") %>% 
  select(Subgroup, Value, everything())

## Total Residual
y1b <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Total", 
         Value = "Residual") %>% 
  select(Subgroup, Value, everything())

## Age
y2 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  group_by(ENROLLEE_AGE > 75) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Age", 
         Value = ifelse(`ENROLLEE_AGE > 75` == "FALSE", "LE75", "M75")) %>% 
  select(Subgroup, Value, everything(), -`ENROLLEE_AGE > 75`)

## Sex
y3 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  group_by(sex) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Sex", 
         Value = sex) %>% 
  select(Subgroup, Value, everything(), -sex)

## Race
y4 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  group_by(race) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Race", 
         Value = race) %>% 
  select(Subgroup, Value, everything(), -race)

## Urbanicity
y5 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  group_by(urban) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Urbanicity", 
         Value = ifelse(urban == 1, "urban", "nonurban")) %>% 
  select(Subgroup, Value, everything(), -urban)

## SES Category
y6 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  group_by(ses_tertile) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "SES Cat", 
         Value = ifelse(ses_tertile == 0, "L",
                        ifelse(ses_tertile == 1, "M", "H"))) %>% 
  select(Subgroup, Value, everything(), -ses_tertile)

## BRFSS Base
y7 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  filter(!is.na(X_bmi_Mean)) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "BRFSS", 
         Value = "brfss0") %>% 
  select(Subgroup, Value, everything())

## BRFSS Adj
y7a <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  filter(!is.na(X_bmi_Mean)) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "BRFSS", 
         Value = "brfss") %>% 
  select(Subgroup, Value, everything())

## RC4
y8 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  summarise(across(cvd_rc:kidn_rc, sum)) %>% 
  mutate(Subgroup = "Total", 
         Value = "RC4") %>% 
  select(Subgroup, Value, everything())

colnames(y8) <-  sub("_rc*", "", colnames(y8))

## Region
y9 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr)) %>% 
  group_by(region) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Region", 
         Value = ifelse(region == 1, "W",
                        ifelse(region == 2, "MW", 
                               ifelse(region == 3, "S", "NE")))) %>% 
  select(Subgroup, Value, everything(), -region)

## Race Urban
y10 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr) & urban == 1) %>% 
  group_by(race) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Race Urban", 
         Value = race) %>% 
  select(Subgroup, Value, everything(), -race)

## Race Non-urban
y11 <- dt.dead.enrollee %>% 
  filter(!is.na(no2_1yr) & urban == 0) %>% 
  group_by(race) %>% 
  summarise(across(allcuz:kidn, sum)) %>% 
  mutate(Subgroup = "Race Non-urban", 
         Value = race) %>% 
  select(Subgroup, Value, everything(), -race)

## Combine
y <- y1 %>% 
  add_row(y1a) %>% 
  add_row(y1b) %>% 
  add_row(y2) %>% 
  add_row(y3) %>% 
  add_row(y4) %>% 
  add_row(y5) %>% 
  add_row(y6) %>% 
  add_row(y7) %>% 
  add_row(y7a) %>% 
  add_row(y8) %>% 
  add_row(y9) %>% 
  add_row(y10) %>% 
  add_row(y11) %>% 
  mutate(Index = "NO2") %>% 
  select(Index, everything())
```

# PM2.5 and NO2
```{r - Combine PM2.5 and NO2}
death.summary <- x %>% 
  add_row(y) %>% 
  pivot_longer(cols = allcuz:kidn,
               names_to = "Outcome",
               values_to = "Death") %>% 
  merge(Outcome.to.Cause) %>% 
  select(Index, Cause, Subgroup, Value, Death) %>% 
  arrange(Index, Subgroup, Value)

save(death.summary, file = here('output','analysis','death-summary.RDa'))
write.csv(death.summary, 
          file = here('output','analysis','death-summary.csv'))
```













